### ISSUE TITLE
unknown feature `llvm_asm`

### ISSUE THREAD

**Issue by felicityin** [nervosnetwork/capsule#68]
```
$ capsule build --release
Building contract nft-validator
   Compiling ckb-std v0.9.0
error[E0635]: unknown feature `llvm_asm`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ckb-std-0.9.0/src/lib.rs:12:12
   |
12 | #![feature(llvm_asm)]
   |            ^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `ckb-std` due to previous error
error: docker container exit with code Some(101)

```

```
$ capsule --version
Capsule 0.8.0

$ ckb-cli --version
ckb-cli 0.103.0 (1dd9cd7 2022-05-27)
```

**Comment by TheWaWaR** [comment]
Please also provide your `capsule.toml` file, since the docker image which used to build the project is matter.

**Comment by felicityin** [comment]
capsule.toml
```
# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."
# toolchain = "nightly-2021-12-25"
# docker_image = "thewawar/ckb-capsule:2021-12-25"

# capsule version
version = "0.8.0"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "nft-validator"
template_type = "Rust"
```

**Comment by TheWaWaR** [comment]
The default docker image used in capsule `v0.8.0` is `thewawar/ckb-capsule:2022-08-01` which use toolchain `nightly-2022-08-01`, and this rustc don't recognize `#![feature(llvm_asm)]`, since this `feature` was already removed now.

You may have three choice:
1. downgrade capsule from `v0.8.0` to `v0.7.3`
2. keep using capsule `v0.8.0`, and upgrade `ckb-std` from `v0.9.0` to `v0.10.0`
3. keep using capsule `v0.8.0`, and change `capsule.toml` to (uncomment the `[rust]` section):
```toml
# capsule version
version = "0.8.0"
# path of deployment config file
deployment = "deployment.toml"

[rust]
# path of rust contracts workspace directory,
# a `Cargo.toml` file is expected under the directory.
workspace_dir = "."
toolchain = "nightly-2021-12-25"
docker_image = "thewawar/ckb-capsule:2021-12-25"

[[contracts]]
name = "nft-validator"
template_type = "Rust"
```

**Comment by felicityin** [comment]
> The default docker image used in capsule `v0.8.0` is `thewawar/ckb-capsule:2022-08-01` which use toolchain `nightly-2022-08-01`, and this rustc don't recognize `#![feature(llvm_asm)]`, since this `feature` was already removed now.
> 
> You may have three choice:
> 
> 1. downgrade capsule from `v0.8.0` to `v0.7.3`
> 2. keep using capsule `v0.8.0`, and upgrade `ckb-std` from `v0.9.0` to `v0.10.0`
> 3. keep using capsule `v0.8.0`, and change `capsule.toml` to (uncomment the `[rust]` section):
> 
> ```toml
> [rust]
> # path of rust contracts workspace directory,
> # a `Cargo.toml` file is expected under the directory.
> workspace_dir = "."
> toolchain = "nightly-2021-12-25"
> docker_image = "thewawar/ckb-capsule:2021-12-25"
> 
> # capsule version
> version = "0.8.0"
> # path of deployment config file
> deployment = "deployment.toml"
> 
> [[contracts]]
> name = "nft-validator"
> template_type = "Rust"
> ```

Thanks very much.

**Comment by felicityin** [comment]
May I ask how to upgrade ckb-std from v0.9.0 to v0.10.0?

**Comment by felicityin** [comment]
I’ve downgrade capsule from v0.8.0 to v0.7.3, and it looks good. But there is another problem when I deploy contract.
```
$ capsule deploy --address ckt1qyqw8yx5hx6vwcm7eqren0d0v39wvfwdhy3q2807pp --fee 0.01
thread 'main' panicked at 'rpc call get_block_by_number: error decoding response body: EOF while parsing a value at line 1 column 0

Caused by:
    EOF while parsing a value at line 1 column 0', src/wallet/rpc.rs:157:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by TheWaWaR** [comment]
Do you have a `ckb` node started? If your ckb node can't access through the default url (which is `http://localhost:8114`), above error will happen.

You may use `capsule deploy --api <url> ...` to specify the ckb node url. Use a public node is ok: https://github.com/nervosnetwork/ckb/wiki/Public-JSON-RPC-nodes (you may need proxy in some regions)

**Comment by felicityin** [comment]
I started ckb node in this way:
```
git clone https://github.com/cryptape/lumos-ckit-internal.git
cd lumos-ckit-internal/devtools/docker
docker compose up --build
```
```
lsof -i:8114
COMMAND    PID  USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
ckb-cli 959376 aping   12u  IPv4 5485885      0t0  TCP localhost:59826->localhost:8114 (ESTABLISHED)
```
And there is still problem after I specify the ckb node url:
```
$ capsule deploy --api http://localhost:8114 --address ckt1qyqw8yx5hx6vwcm7eqren0d0v39wvfwdhy3q2807pp --fee 0.01 
thread 'main' panicked at 'rpc call get_block_by_number: error decoding response body: EOF while parsing a value at line 1 column 0

Caused by:
    EOF while parsing a value at line 1 column 0', src/wallet/rpc.rs:157:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by TheWaWaR** [comment]
You can use follow commands to the test the url:
```shell
# test if there is a server bind to this address
curl http://localhost:8114

# test if the server is ckb node
ckb-cli --url http://localhost:8114 rpc get_tip_header
```

**Comment by felicityin** [comment]
```
$ ckb-cli --url http://localhost:8114 rpc get_tip_header
compact_target: 0x20010000
dao: 0xaa779abd8dbce7a26765087a2f3824007b152f821f38e302007d7ad95622ff06
epoch: "0x20001000ddc {number: 3548, index: 1, length: 2}"
extra_hash: 0x0000000000000000000000000000000000000000000000000000000000000000
hash: 0xff3675d821a7a2ba0403fd12cea893bd450e2ba24ecba60dfc2e815cf1efbc10
nonce: 0x53d3f7614fa2f23453e2eb992840dec2
number: 7097
parent_hash: 0x0d66a5738c878049cebf129414fbf92e9267dede90c236a2a0ceeaaee4d79220
proposals_hash: 0x0000000000000000000000000000000000000000000000000000000000000000
timestamp: "1661833627662 (2022-08-30 12:27:07.662 +08:00)"
transactions_root: 0x5716c17fa721d5e228427e50feba4e65bab3c4ef9735ec8165753780cb18658c
version: 0

$ curl http://localhost:8114
Used HTTP Method is not allowed. POST or OPTIONS is required
```

**Comment by TheWaWaR** [comment]
That is strange, the above error happen when rpc client get the genesis block, you may use ckb-cli to test if you can get genesis block:
```
ckb-cli --url http://localhost:8114  rpc get_block_by_number --number 0
```

**Comment by felicityin** [comment]
> That is strange, the above error happen when rpc client get the genesis block, you may use ckb-cli to test if you can get genesis block:
> 
> ```
> ckb-cli --url http://localhost:8114  rpc get_block_by_number --number 0
> ```

It seems I can get genesis block:
```
...
   outputs:
      - capacity: "117.0"
        lock:
          args: 0x
          code_hash: 0x0000000000000000000000000000000000000000000000000000000000000000
          hash_type: data
        type: ~
      - capacity: "117.0"
        lock:
          args: 0x
          code_hash: 0x0000000000000000000000000000000000000000000000000000000000000000
          hash_type: data
        type: ~
    outputs_data:
      - 0x02000000f1e9baa862d4c61ccdea49a810a406c47416b2eb92df7e9eac88852c0696bcbd03000000f1e9baa862d4c61ccdea49a810a406c47416b2eb92df7e9eac88852c0696bcbd01000000
      - 0x02000000f1e9baa862d4c61ccdea49a810a406c47416b2eb92df7e9eac88852c0696bcbd03000000f1e9baa862d4c61ccdea49a810a406c47416b2eb92df7e9eac88852c0696bcbd04000000
    version: 0
    witnesses:
      - 0xd84055193b4c5278f22bc6c2aa6f50ff046547f9a7bb2ff6747c3b235a131aa83270847006f57a04970abfe854198a4b2ea9e369598f3cd44d2ea22d8efc30e701
uncles: []
```
