### ISSUE TITLE
Consider building rust contracts with cross

### ISSUE THREAD

**Issue by blckngm** [nervosnetwork/capsule#84]
Pros:

* More familiar for rust devs.
* Smaller images (no rust).
* Can use any rust version.
* Better support for cargo commands and options, e.g. `cross build -v`, `cross clippy` etc (#35).
* Easier to maintain. `capsule build` can be a thin wrapper of `cross`.

~It mostly already works, I had to make one small change to cross:~

~https://github.com/cross-rs/cross/commit/c632612f99f7387d18d8eac0550b2a96596e1f2e~

Add this configuration (`Cross.toml`) to a capsule project:

```toml
[build]
default-target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
# Both image works
# image = "thewawar/ckb-capsule:2022-08-01"
image = "nervos/ckb-riscv-gnu-toolchain:focal-20230214"
```

Then I can `cross +nightly build -p some_contract`
